# -*- coding: utf-8 -*-
"""TF simulation gold

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1iq51rx5is-87V9JNJiuNSmR851lA_2
"""

!pip install ta optuna twelvedata kagglehub==0.4.1 -q

# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "XAUUSD_ohlc.csv"

# Load the latest version
df = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "fajar16/gold-ohlc",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

# print("First 5 records:", df.head())
print(df)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from dataclasses import dataclass
from typing import List, Optional

# ==========================================
# 1. STRUKTUR DATA TRADE
# ==========================================
@dataclass
class Trade:
    entry_time: pd.Timestamp
    entry_price: float
    type: str  # 'BUY' or 'SELL'
    sl_price: float
    tp_price: float
    sl_pips: float
    tp_pips: float

    # Akan diisi saat exit
    exit_time: pd.Timestamp = None
    exit_price: float = None
    pips_gained: float = 0.0
    status: str = 'OPEN'

@dataclass
class PendingOrder:
    create_time: pd.Timestamp
    type: str
    price: float
    sl_pips: float
    tp_pips: float

# ==========================================
# 2. FRAMEWORK ENGINE (MULTI-ORDER SUPPORT)
# ==========================================
class GoldPipEngine:
    def __init__(self, data: pd.DataFrame, pip_scale: float = 0.1):
        self.data = data.copy()
        self.pip_scale = pip_scale
        self.trades: List[Trade] = []

        # [UBAH] Menjadi List untuk menampung > 1 trade
        self.active_trades: List[Trade] = []
        self.pending_order: Optional[PendingOrder] = None

    def _calculate_pips(self, entry, exit, direction):
        diff = exit - entry
        if direction == 'SELL':
            diff = -diff
        return diff / self.pip_scale

    def run_backtest(self, signals: pd.Series, sl_pips: int, tp_pips: int,
                     order_type: str = 'STOP', pending_dist_pips: int = 0,
                     max_open_trades: int = 2, min_dist_between_orders: int = 100):
        """
        max_open_trades: Maksimal trade aktif bersamaan (default 2)
        min_dist_between_orders: Jarak minimal antar entry dalam Pips (default 100)
        """
        print(f"Backtest Multi-Order ({order_type})... Max Trades: {max_open_trades}, Min Dist: {min_dist_between_orders} pips")

        sl_dist_price = sl_pips * self.pip_scale
        tp_dist_price = tp_pips * self.pip_scale
        pending_dist_price = pending_dist_pips * self.pip_scale
        min_dist_price = min_dist_between_orders * self.pip_scale # Konversi ke harga

        # Loop Bar-per-Bar
        for i in range(1, len(self.data)):
            curr_time = self.data.index[i]
            curr_open = self.data['Open'].iloc[i]
            curr_high = self.data['High'].iloc[i]
            curr_low = self.data['Low'].iloc[i]

            # ===============================================
            # FASE 1: CEK PENDING ORDER -> VALIDASI JARAK -> ENTRY
            # ===============================================
            # Cek trigger jika Pending Order ada DAN slot trade masih tersedia
            if self.pending_order is not None and len(self.active_trades) < max_open_trades:
                po = self.pending_order
                triggered = False
                fill_price = po.price

                # --- LOGIKA TRIGGER (Sama seperti sebelumnya) ---
                if 'BUY' in po.type:
                    if 'STOP' in po.type and curr_high >= po.price:
                        triggered = True
                        if curr_open > po.price: fill_price = curr_open
                    elif 'LIMIT' in po.type and curr_low <= po.price:
                        triggered = True
                        if curr_open < po.price: fill_price = curr_open

                elif 'SELL' in po.type:
                    if 'STOP' in po.type and curr_low <= po.price:
                        triggered = True
                        if curr_open < po.price: fill_price = curr_open
                    elif 'LIMIT' in po.type and curr_high >= po.price:
                        triggered = True
                        if curr_open > po.price: fill_price = curr_open

                # --- VALIDASI JARAK & EKSEKUSI ---
                if triggered:
                    # Cek Jarak dengan trade yang SUDAH ADA
                    is_distance_valid = True
                    for trade in self.active_trades:
                        dist = abs(fill_price - trade.entry_price)
                        if dist < min_dist_price:
                            is_distance_valid = False
                            break

                    # Entry hanya jika jarak aman (atau jika ini trade pertama)
                    if is_distance_valid:
                        trade_type = 'BUY' if 'BUY' in po.type else 'SELL'

                        # Set SL/TP Individual
                        if trade_type == 'BUY':
                            sl = fill_price - sl_dist_price
                            tp = fill_price + tp_dist_price
                        else:
                            sl = fill_price + sl_dist_price
                            tp = fill_price - tp_dist_price

                        new_trade = Trade(
                            entry_time=curr_time, entry_price=fill_price, type=trade_type,
                            sl_price=sl, tp_price=tp, sl_pips=sl_pips, tp_pips=tp_pips
                        )
                        self.active_trades.append(new_trade)
                        self.pending_order = None # Hapus antrian
                    else:
                        # Opsional: Hapus pending order jika terlalu dekat,
                        # atau biarkan untuk candle berikutnya (di sini kita biarkan)
                        pass

            # ===============================================
            # FASE 2: CEK EXIT SEMUA POSISI AKTIF
            # ===============================================
            # Kita iterate copy list [:] agar aman saat menghapus item dalam loop
            for t in self.active_trades[:]:
                exit_price = None
                status = None

                if t.type == 'BUY':
                    if curr_low <= t.sl_price:
                        exit_price = t.sl_price if curr_open >= t.sl_price else curr_open
                        status = 'SL_HIT'
                    elif curr_high >= t.tp_price:
                        exit_price = t.tp_price if curr_open <= t.tp_price else curr_open
                        status = 'TP_HIT'

                elif t.type == 'SELL':
                    if curr_high >= t.sl_price:
                        exit_price = t.sl_price if curr_open <= t.sl_price else curr_open
                        status = 'SL_HIT'
                    elif curr_low <= t.tp_price:
                        exit_price = t.tp_price if curr_open >= t.tp_price else curr_open
                        status = 'TP_HIT'

                if exit_price is not None:
                    t.exit_time = curr_time
                    t.exit_price = exit_price
                    t.status = status
                    t.pips_gained = self._calculate_pips(t.entry_price, t.exit_price, t.type)

                    self.trades.append(t)       # Masukkan ke history
                    self.active_trades.remove(t) # Hapus dari active trades

            # ===============================================
            # FASE 3: MANAGEMEN PENDING ORDER
            # ===============================================
            # Kita hanya buat pending order jika slot masih ada
            if len(self.active_trades) < max_open_trades:
                signal = signals.iloc[i-1]
                prev_close = self.data['Close'].iloc[i-1]

                if signal != 0:
                    order_price = 0.0
                    full_type = ""

                    if signal == 1:
                        full_type = f'BUY_{order_type}'
                        order_price = prev_close + pending_dist_price if order_type == 'STOP' else prev_close - pending_dist_price
                    elif signal == -1:
                        full_type = f'SELL_{order_type}'
                        order_price = prev_close - pending_dist_price if order_type == 'STOP' else prev_close + pending_dist_price

                    self.pending_order = PendingOrder(
                        create_time=curr_time, type=full_type, price=order_price,
                        sl_pips=sl_pips, tp_pips=tp_pips
                    )

    def get_analysis(self):
        if not self.trades:
            return "Tidak ada trade yang terjadi."

        df_trades = pd.DataFrame([t.__dict__ for t in self.trades])

        # Stats Dasar
        total_pips = df_trades['pips_gained'].sum()
        win_trades = df_trades[df_trades['pips_gained'] > 0]
        loss_trades = df_trades[df_trades['pips_gained'] <= 0]
        win_rate = len(win_trades) / len(df_trades) * 100

        # Consecutives
        max_con_wins = 0
        max_con_losses = 0
        cur_wins = 0
        cur_losses = 0
        for pips in df_trades['pips_gained']:
            if pips > 0:
                cur_wins += 1; cur_losses = 0
                max_con_wins = max(max_con_wins, cur_wins)
            else:
                cur_losses += 1; cur_wins = 0
                max_con_losses = max(max_con_losses, cur_losses)

        # Drawdown
        df_trades['cumulative_pips'] = df_trades['pips_gained'].cumsum()
        df_trades['peak'] = df_trades['cumulative_pips'].cummax()
        df_trades['drawdown'] = df_trades['cumulative_pips'] - df_trades['peak']
        max_dd = df_trades['drawdown'].min()

        stats = {
            'Total Trades': len(df_trades),
            'Net Pips': f"{total_pips:.1f}",
            'Win Rate': f"{win_rate:.2f}%",
            'Avg Win': f"{win_trades['pips_gained'].mean():.1f}" if not win_trades.empty else "0",
            'Avg Loss': f"{loss_trades['pips_gained'].mean():.1f}" if not loss_trades.empty else "0",
            'Max Drawdown': f"{max_dd:.1f}",
            'Max Consec Wins': max_con_wins,
            'Max Consec Losses': max_con_losses
        }
        return stats, df_trades

import pandas as pd
import numpy as np
# Menghapus data di mana index hari adalah Sabtu (5) atau Minggu (6)
df['datetime'] = pd.to_datetime(df['datetime'])
df_1h = df.set_index('datetime')

df_1h = df_1h[df_1h.index.dayofweek < 5]
# df_1h = df_1h[:'2025-11':]
# Cek hasil
print(df_1h)

import yfinance as yf

# Download data
df_1h = yf.download("GC=F", period="2y", interval="1h")

# 1. Hapus level teratas (Price)
df_1h.columns = df_1h.columns.droplevel(1) # atau droplevel(0) tergantung struktur
# df_1h = df_1h['2024-02':]
print(df_1h)

# # ==========================================
# # 3. CONTOH PENGGUNAAN (Implementasi Strategi)
# # ==========================================

# # 1. Load Data (Gunakan data dummy atau CSV Anda)
# # Untuk test, kita buat data random walk yang mirip Gold
# dates = pd.date_range(start='2023-01-01', periods=10000, freq='1h')
# price = 2000 + np.random.randn(10000).cumsum()
data_gold = df_1h.copy()

# ==========================================
# 2. DEFINISIKAN LOGIKA SINYAL (EMA + Price Action)
# ==========================================

# 1. Hitung Indikator EMA
ema_period = 10  # Bisa diganti ke 20, 100, atau 200
data_gold['EMA'] = data_gold['Close'].ewm(span=ema_period, adjust=False).mean()

# 2. Siapkan Data Candle (Current & Previous)
# Shift(1) = Candle Sebelumnya (Candle 1)
# Tidak ada Shift = Candle Sekarang (Candle 2 / Trigger)
prev_open = data_gold['Open'].shift(1)
prev_close = data_gold['Close'].shift(1)
prev_high = data_gold['High'].shift(1)
prev_low = data_gold['Low'].shift(1)
prev_ema = data_gold['EMA'].shift(1)
prev_vol = data_gold['Volume'].shift(1)

curr_open = data_gold['Open']
curr_close = data_gold['Close']
curr_high = data_gold['High']
curr_low = data_gold['Low']
curr_ema = data_gold['EMA']
curr_vol = data_gold['Volume']

# --- LOGIKA BULLISH (BUY) ---
# Syarat 1: Candle 1 Bearish (Merah)
c1_bear = prev_close < prev_open
# Syarat 2: Candle 2 Bullish (Hijau)
c2_bull = curr_close > curr_open
# Syarat 3: Close Candle 2 > High Candle 1 (Breakout High sebelumnya)
c3_break_high = curr_close > prev_high
# Syarat 4: TIDAK MENYENTUH EMA (Validasi Tren)
# Artinya Low kedua candle harus benar-benar di ATAS EMA
c4_clean_trend = (prev_low > prev_ema) & (curr_low > curr_ema)

buy_setup = c1_bear & c2_bull & c3_break_high & c4_clean_trend

# --- LOGIKA BEARISH (SELL) ---
# Syarat 1: Candle 1 Bullish (Hijau)
c1_bull = prev_close > prev_open
# Syarat 2: Candle 2 Bearish (Merah)
c2_bear = curr_close < curr_open
# Syarat 3: Close Candle 2 < Low Candle 1 (Breakout Low sebelumnya)
c3_break_low = curr_close < prev_low
# Syarat 4: TIDAK MENYENTUH EMA (Validasi Tren)
# Artinya High kedua candle harus benar-benar di BAWAH EMA
c4_clean_trend_bear = (prev_high < prev_ema) & (curr_high < curr_ema)

sell_setup = c1_bull & c2_bear & c3_break_low & c4_clean_trend_bear

# 3. Gabungkan menjadi Sinyal
signals = pd.Series(0, index=data_gold.index)
signals[buy_setup] = 1   # Buy Signal
signals[sell_setup] = -1 # Sell Signal
# 3. Jalankan Custom Engine
# Ingat: pip_scale=0.1 untuk XAUUSD standar.
engine = GoldPipEngine(data_gold, pip_scale=0.1)

# Input: SL 50 Pips ($5), TP 100 Pips ($10) -> Risk Reward 1:2
engine.run_backtest(
    signals,
    sl_pips=200,
    tp_pips=400,
    order_type='STOP',
    pending_dist_pips=35,
    max_open_trades=2,             # <--- Parameter Baru
    min_dist_between_orders=105    # <--- Parameter Baru
)
# 4. Analisis Hasil
stats, trade_history = engine.get_analysis()

print("\n=== LAPORAN PERFORMA (PIPS) ===")
for k, v in stats.items():
    print(f"{k:<25}: {v}")

# 5. Visualisasi Cumulative Pips
plt.figure(figsize=(12, 6))
trade_history['cumulative_pips'].plot()
plt.title("Growth Curve (Net Pips Accumulation)")
plt.xlabel("Trade Number")
plt.ylabel("Pips")
plt.grid(True, alpha=0.3)
plt.axhline(0, color='red', linestyle='--')
plt.show()

# Lihat 5 trade terakhir untuk verifikasi logika
print("\n5 Trade Terakhir:")
print(trade_history[['entry_time', 'type', 'entry_price', 'exit_price', 'status', 'pips_gained']].tail())

import pandas as pd

# 1. Konversi waktu dan sorting
# Reset index first if 'entry_time' is already the index to treat it as a column
if 'entry_time' not in trade_history.columns and trade_history.index.name == 'entry_time':
    trade_history = trade_history.reset_index()

trade_history['entry_time'] = pd.to_datetime(trade_history['entry_time'])
trade_history = trade_history.sort_values('entry_time')

# 2. Set index untuk mempermudah grouping
trade_history.set_index('entry_time', inplace=True)

# 3. Agregasi Bulanan
# Menggunakan 'ME' (Month End) untuk pandas versi terbaru
monthly_summary = trade_history.resample('ME').agg({
    'pips_gained': ['sum', 'count'],
    'drawdown': 'min'
})

# Perampingan nama kolom
monthly_summary.columns = ['Total_Pips', 'Trade_Count', 'Max_Drawdown_Pips']

# 4. Menghitung Win Rate per bulan
tp_count = trade_history[trade_history['status'] == 'TP_HIT'].resample('ME').size()
monthly_summary['Win_Rate_%'] = (tp_count / monthly_summary['Trade_Count'] * 100).fillna(0)

# 5. Menghitung Profit Factor (Gross Profit / Gross Loss) per bulan
gross_profit = trade_history[trade_history['pips_gained'] > 0].resample('ME')['pips_gained'].sum()
gross_loss = trade_history[trade_history['pips_gained'] < 0]['pips_gained'].abs().resample('ME').sum()
monthly_summary['Profit_Factor'] = (gross_profit / gross_loss).replace([float('inf'), -float('inf')], 2.0) # Cap di 2.0 jika tidak ada loss

print(monthly_summary.tail(12)) # Menampilkan 12 bulan terakhir

!pip install yfinance

!pip install yfinance -q
import yfinance as yf

# Download data
df = yf.download("GC=F", period="2y", interval="1h")

# 1. Hapus level teratas (Price)
df.columns = df.columns.droplevel(1) # atau droplevel(0) tergantung struktur

# 2. Reset index agar 'Datetime' jadi kolom biasa
# df = df.reset_index()

print(df.head())
df.to_csv('gold_ohlc.csv')

# Cek jumlah null di setiap kolom
null_counts = df.isnull().sum()
print("Jumlah data kosong per kolom:")
print(null_counts)

# Cek total seluruh data null di dataset
total_null = df.isnull().sum().sum()
print(f"\nTotal semua data kosong: {total_null}")